name: Update Changelog

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli
          
      - name: Generate changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git add CHANGELOG.md && git commit -m "Update changelog [skip ci]" && git push)